name:                 Haskell-Full-check
version:              0.1.0.0
visibility:           public
id:                   Haskell-Full-check-0.1.0.0-inplace
key:                  Haskell-Full-check-0.1.0.0-inplace
license:              MIT
maintainer:           79172019+XessX@users.noreply.github.com
author:               XessX
synopsis:             A tagless haskell interpreter
category:             Development
abi:                  inplace
exposed:              True
exposed-modules:
    Abstract CodeGen Eval Length Partial Pretty TestSuite Trace
    TypeClasses

import-dirs:
    /Users/jubair/Haskell_Full_check/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Haskell-Full-check-0.1.0.0/build

library-dirs:
    /Users/jubair/Haskell_Full_check/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Haskell-Full-check-0.1.0.0/build

library-dirs-static:
    /Users/jubair/Haskell_Full_check/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Haskell-Full-check-0.1.0.0/build

dynamic-library-dirs:
    /Users/jubair/Haskell_Full_check/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Haskell-Full-check-0.1.0.0/build

data-dir:             /Users/jubair/Haskell_Full_check/.
hs-libraries:         HSHaskell-Full-check-0.1.0.0-inplace
depends:
    HUnt-1.6.2.0-07122a86 base-4.17.2.1 hnt-0.9.0.8-d025cfb0 mtl-2.2.2
    prttyprntr-1.7.1-eb3028d5 template-haskell-2.19.0.0 text-2.0.2

haddock-interfaces:
    /Users/jubair/Haskell_Full_check/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Haskell-Full-check-0.1.0.0/doc/html/Haskell-Full-check/Haskell-Full-check.haddock

haddock-html:
    /Users/jubair/Haskell_Full_check/dist-newstyle/build/aarch64-osx/ghc-9.4.8/Haskell-Full-check-0.1.0.0/doc/html/Haskell-Full-check
