name:                 haskell-project
version:              0.1.0.0
visibility:           public
id:                   haskell-project-0.1.0.0-inplace
key:                  haskell-project-0.1.0.0-inplace
license:              MIT
maintainer:           79172019+XessX@users.noreply.github.com
author:               XessX
synopsis:             A tagless haskell interpreter
category:             Development
abi:                  inplace
exposed:              True
exposed-modules:      Hx Len Pp Runs TestSuite TypesClasses
import-dirs:
    /Users/jubair/haskell-project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/haskell-project-0.1.0.0/build

library-dirs:
    /Users/jubair/haskell-project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/haskell-project-0.1.0.0/build

library-dirs-static:
    /Users/jubair/haskell-project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/haskell-project-0.1.0.0/build

dynamic-library-dirs:
    /Users/jubair/haskell-project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/haskell-project-0.1.0.0/build

data-dir:             /Users/jubair/haskell-project/.
hs-libraries:         HShaskell-project-0.1.0.0-inplace
depends:
    HUnt-1.6.2.0-07122a86 base-4.17.2.1 prttyprntr-1.7.1-eb3028d5
    text-2.0.2

haddock-interfaces:
    /Users/jubair/haskell-project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/haskell-project-0.1.0.0/doc/html/haskell-project/haskell-project.haddock

haddock-html:
    /Users/jubair/haskell-project/dist-newstyle/build/aarch64-osx/ghc-9.4.8/haskell-project-0.1.0.0/doc/html/haskell-project
